/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Listar_Solicitudes_de_Amistad.java
 *
 * Created on 12-08-2011, 04:40:24 PM
 */
package face;

import java.io.RandomAccessFile;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;

/**
 *
 * @author Josue
 */
public class Listar_Solicitudes_de_Amistad extends javax.swing.JFrame {

    /** Creates new form Listar_Solicitudes_de_Amistad */
    public Listar_Solicitudes_de_Amistad() {
        initComponents();
        
        String solicitante;
        boolean confirmado,decidido;
        
        try{
            
           
            
            
            
           RandomAccessFile amigos=new RandomAccessFile("Cuentas/"+Profile.Email+"/manageFriends.fbn","rw");
           amigos.seek(0);
           
           while(amigos.getFilePointer() < amigos.length()){
               
               solicitante=amigos.readUTF();
               confirmado=amigos.readBoolean();
               decidido=amigos.readBoolean();
               
               if(!confirmado && !decidido){
                   
                   Solicitudesbox.addItem(solicitante);
               }
               
           }
           
            
            
        }
        catch(Exception error){
            
            
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        Label4 = new javax.swing.JLabel();
        Solicitudesbox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        Agregarbtn = new javax.swing.JButton();
        Regresarbtn = new javax.swing.JButton();
        Rechazobtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel3.setText("Data");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(979, 510));
        setResizable(false);
        getContentPane().setLayout(null);

        Solicitudesbox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SolicitudesboxMouseClicked(evt);
            }
        });
        Solicitudesbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SolicitudesboxActionPerformed(evt);
            }
        });
        Solicitudesbox.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                SolicitudesboxPropertyChange(evt);
            }
        });
        getContentPane().add(Solicitudesbox);
        Solicitudesbox.setBounds(66, 132, 344, 20);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(" Amigos por confirmar");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(66, 112, 180, 14);

        Agregarbtn.setText("Aceptar Solicitud");
        Agregarbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgregarbtnMouseClicked(evt);
            }
        });
        getContentPane().add(Agregarbtn);
        Agregarbtn.setBounds(611, 175, 176, 23);

        Regresarbtn.setText("Regresar ");
        Regresarbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegresarbtnMouseClicked(evt);
            }
        });
        getContentPane().add(Regresarbtn);
        Regresarbtn.setBounds(611, 250, 176, 23);

        Rechazobtn.setText("Rechazar Solicitud");
        Rechazobtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RechazobtnMouseClicked(evt);
            }
        });
        getContentPane().add(Rechazobtn);
        Rechazobtn.setBounds(611, 209, 176, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/face/s.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 980, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SolicitudesboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SolicitudesboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SolicitudesboxActionPerformed

    private void SolicitudesboxPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_SolicitudesboxPropertyChange
    
        
         
    }//GEN-LAST:event_SolicitudesboxPropertyChange

    private void AgregarbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarbtnMouseClicked
        
       
            String comparacion;
            String persona=Solicitudesbox.getSelectedItem().toString();
            
           
                        
                     try{
                         
                         RandomAccessFile f=new RandomAccessFile("Cuentas/"+Profile.Email+"/manageFriends.fbn","rw");
                         f.seek(0);
                         
                         while(f.getFilePointer() < f.length()){
                             
                             comparacion=f.readUTF();
                             
                             if(comparacion.equals(persona)){
                                 
                                 f.writeBoolean(true);
                                 f.writeBoolean(true);
                                 
                                break;
                             }
                             
                             f.readBoolean();
                             f.readBoolean();
                             
                             
                         }
                         
                         RandomAccessFile g=new RandomAccessFile("Cuentas/"+persona+"/manageFriends.fbn","rw");
                         g.seek(g.length());
                         
                         g.writeUTF(Profile.Email);
                         g.writeBoolean(true);
                         g.writeBoolean(true);
                         
                         
                         
                     }
                      
                     catch(Exception e){
                         
                     }
                     
                     JOptionPane.showMessageDialog(null, "Has aceptado la solicitud de "+persona+ " ahora el(ella) y tu son amigos !!",
                        "Solicitudes", JOptionPane.INFORMATION_MESSAGE);
                        
                        Solicitudesbox.removeItem(persona);
                     
        
           
    }//GEN-LAST:event_AgregarbtnMouseClicked

    private void RegresarbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarbtnMouseClicked
        
        Perfil l=new Perfil();
        l.setVisible(true);
        dispose();
        
        
        
    }//GEN-LAST:event_RegresarbtnMouseClicked

    private void SolicitudesboxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SolicitudesboxMouseClicked
        
      
    }//GEN-LAST:event_SolicitudesboxMouseClicked

    private void RechazobtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RechazobtnMouseClicked
       
         String comparation;
            String solicitant=Solicitudesbox.getSelectedItem().toString();
            
            JOptionPane.showMessageDialog(null, "Has rechazado la solicitud de "+solicitant+" !!",
                        "Solicitudes", JOptionPane.INFORMATION_MESSAGE);
                        
                        Solicitudesbox.removeItem(solicitant);
                        
                     try{
                         
                         RandomAccessFile f=new RandomAccessFile("Cuentas/"+Profile.Email+"/manageFriends.fbn","rw");
                         f.seek(0);
                         
                         while(f.getFilePointer() < f.length()){
                             
                             comparation=f.readUTF();
                             
                             if(comparation.equals(solicitant)){
                                 
                                 f.writeBoolean(false);
                                 f.writeBoolean(true);
                                 
                                 break;
                             }
                             
                             f.readBoolean();
                             f.readBoolean();
                             
                             
                         }
                         
                         
                         
                         
                     }
                     
                     catch(Exception e){
                         
                     }
           
        
        
        
        
        
        
        
    }//GEN-LAST:event_RechazobtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Listar_Solicitudes_de_Amistad().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregarbtn;
    private javax.swing.JLabel Label4;
    private javax.swing.JButton Rechazobtn;
    private javax.swing.JButton Regresarbtn;
    private javax.swing.JComboBox Solicitudesbox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
