package face;

import java.io.RandomAccessFile;
import javax.swing.JOptionPane;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LogIn.java
 *
 * Created on 11-24-2011, 05:27:31 PM
 */
/**
 *
 * @author Josue
 */
public class LogIn extends javax.swing.JFrame {

    /** Creates new form LogIn */
    public LogIn() {
        initComponents();
    }
    
   
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Passwordtxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Emailtxt = new javax.swing.JTextField();
        Loginbtn = new javax.swing.JButton();
        Registrarsebtn = new javax.swing.JButton();
        PasswordLogtxt = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(856, 466));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        jLabel2.setText("Email:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(250, 20, 80, 19);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Password:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(540, 20, 109, 20);

        Emailtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailtxtActionPerformed(evt);
            }
        });
        getContentPane().add(Emailtxt);
        Emailtxt.setBounds(250, 40, 247, 28);

        Loginbtn.setText("LogIn");
        Loginbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginbtnMouseClicked(evt);
            }
        });
        getContentPane().add(Loginbtn);
        Loginbtn.setBounds(760, 40, 89, 23);

        Registrarsebtn.setText("Registrarse");
        Registrarsebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegistrarsebtnMouseClicked(evt);
            }
        });
        getContentPane().add(Registrarsebtn);
        Registrarsebtn.setBounds(560, 220, 160, 23);
        getContentPane().add(PasswordLogtxt);
        PasswordLogtxt.setBounds(540, 40, 211, 30);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/face/facebin4.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -30, 860, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

     
    private void RegistrarsebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrarsebtnMouseClicked
        // TODO add your handling code here:
        try{
        RandomAccessFile Gerencia=new RandomAccessFile("Gerencia.fbn","rw");
        }
        
        catch(Exception error){
            
        }
        
        
        Registro r=new Registro();
        r.setVisible(true);
        dispose();
        
        
        
    }//GEN-LAST:event_RegistrarsebtnMouseClicked

    private void LoginbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginbtnMouseClicked
        // TODO add your handling code here:
        
         
         
         String Email,newEmail,Password,newPassword;
         Boolean Activo=null;
         
         newEmail=(Emailtxt.getText());
         newPassword=PasswordLogtxt.getText();
         
         Registroclass r=new Registroclass();
         
         try{
             
         r.Gere.seek(0);
         
         while(r.Gere.getFilePointer() < r.Gere.length()){
             
         Email=r.Gere.readUTF();
         Password=r.Gere.readUTF();
         Activo=r.Gere.readBoolean();
         
         
         if(newEmail.equals(Email)&& newPassword.equals(Password) && Activo ){
             
             
            
             
             Profile.Email=newEmail;
             VerPerfil vp=new VerPerfil();
             vp.setVisible(true);
             dispose();
         }
        
         
         }
         
         
         
    
         
         
         }
         
         catch(Exception a){
             
         }
         
    }//GEN-LAST:event_LoginbtnMouseClicked

private void EmailtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailtxtActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_EmailtxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Emailtxt;
    private javax.swing.JButton Loginbtn;
    private javax.swing.JPasswordField PasswordLogtxt;
    private javax.swing.JTextField Passwordtxt;
    private javax.swing.JButton Registrarsebtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
