/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Perfil.java
 *
 * Created on 11-28-2011, 02:44:01 PM
 */
package face;

import java.awt.Image;
import java.io.RandomAccessFile;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Josue
 */
public class PerfilDeAmigo extends javax.swing.JFrame {

    /** Creates new form Perfil */
    public PerfilDeAmigo() {
        initComponents();
    this.lbl_Foto.setSize(200,200);
    setFoto();
    
    int contuni=0,posiciones=0,posfechas=0,total;
    Date m=null;
    
    
    
    try{
            
            String friend;
            
            boolean confirmado,decidido;
           RandomAccessFile amigos=new RandomAccessFile("Cuentas/"+Profile.EmaildelAmigo+"/manageFriends.fbn","rw");
           amigos.seek(0);
           
           while(amigos.getFilePointer() < amigos.length()){
               
               friend=amigos.readUTF();
               confirmado=amigos.readBoolean();
               decidido=amigos.readBoolean();
               
               if(confirmado && decidido){
                   
                   Friendspro.addItem(friend);
               }
               
           }
           
            
            
        }
        catch(Exception error){
            
            
        }
    
    
    
    
    
     try{
    RandomAccessFile fg=new RandomAccessFile("Cuentas/"+Profile.EmaildelAmigo+"/Status.fbn","rw");
    
      fg.seek(0);
      
       while(fg.getFilePointer() < fg.length()){
           
           fg.readUTF();
           contuni +=1;
           
       }
       
       total=contuni -1;
    
       
       
       fg.seek(0);
       
       String stats[]=new String[contuni];
       long Fechas[]=new long[contuni];
       
       while(fg.getFilePointer() < fg.length()){
           
           stats[posiciones]=fg.readUTF();
           posiciones +=1;
           
           
       }
       
       
       RandomAccessFile g=new RandomAccessFile("Cuentas/"+Profile.EmaildelAmigo+"/Fechas.fbn","rw");
       
       g.seek(0);
       
       while(g.getFilePointer() < g.length()){
           
           Fechas[posfechas]=g.readLong();
           posfechas +=1;
           
       }
       
       
       
       int newcont=0;
       
       while(total >= 0){
       
       m= new Date(Fechas[total]);
         
       Thougthscmb.addItem(stats[total]+"   "+m);
       
       total -=1;
       
       
       
       
       }
       
       
       
       
    
    }
    catch(Exception r){
        
    }
       
    
    
    
    
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jScrollBar1 = new javax.swing.JScrollBar();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        scrollPane1 = new java.awt.ScrollPane();
        Descripciontxt = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Generotxt = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Nacimientotxt = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Emailtxt = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Telefonotxt = new javax.swing.JLabel();
        Ingresotxt = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Imagetxt = new javax.swing.JLabel();
        lbl_Foto = new javax.swing.JLabel();
        Friendspro = new javax.swing.JComboBox();
        ViewProbtn = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        Prooriginalbtn = new javax.swing.JButton();
        Thougthscmb = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jLabel7.setText("jLabel7");

        jScrollPane3.setViewportView(jTextPane1);

        jScrollPane4.setViewportView(jTextPane2);

        jScrollPane5.setViewportView(jTextPane3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1324, 734));
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(null);

        Descripciontxt.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        Descripciontxt.setForeground(new java.awt.Color(255, 255, 255));
        Descripciontxt.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                DescripciontxtPropertyChange(evt);
            }
        });
        getContentPane().add(Descripciontxt);
        Descripciontxt.setBounds(110, 100, 214, 17);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setText("GENERO:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 140, 83, 28);

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel3.setText("  NAME:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 100, 70, 22);

        Generotxt.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        Generotxt.setForeground(new java.awt.Color(255, 255, 255));
        Generotxt.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                GenerotxtPropertyChange(evt);
            }
        });
        getContentPane().add(Generotxt);
        Generotxt.setBounds(140, 140, 110, 29);

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel4.setText("FECHA DE NACIMIENTO:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 170, 230, 21);

        Nacimientotxt.setForeground(new java.awt.Color(255, 255, 255));
        Nacimientotxt.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                NacimientotxtPropertyChange(evt);
            }
        });
        getContentPane().add(Nacimientotxt);
        Nacimientotxt.setBounds(240, 170, 227, 21);

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel6.setText("EMAIL:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 210, 80, 22);

        Emailtxt.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        Emailtxt.setForeground(new java.awt.Color(255, 255, 255));
        Emailtxt.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                EmailtxtPropertyChange(evt);
            }
        });
        getContentPane().add(Emailtxt);
        Emailtxt.setBounds(120, 200, 300, 33);

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel8.setText("FECHA DE INGRESO AL SISTEMA:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 250, 300, 26);

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel9.setText("TELEFONO:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 320, 130, 19);

        Telefonotxt.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        Telefonotxt.setForeground(new java.awt.Color(255, 255, 255));
        Telefonotxt.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                TelefonotxtPropertyChange(evt);
            }
        });
        getContentPane().add(Telefonotxt);
        Telefonotxt.setBounds(160, 320, 231, 20);

        Ingresotxt.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        Ingresotxt.setForeground(new java.awt.Color(255, 255, 255));
        Ingresotxt.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                IngresotxtPropertyChange(evt);
            }
        });
        getContentPane().add(Ingresotxt);
        Ingresotxt.setBounds(300, 250, 330, 26);

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 24));
        jLabel5.setText("                  MY BIN-STAT");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(380, 10, 477, 39);

        Imagetxt.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                ImagetxtPropertyChange(evt);
            }
        });
        getContentPane().add(Imagetxt);
        Imagetxt.setBounds(721, 168, 163, 185);

        lbl_Foto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(lbl_Foto);
        lbl_Foto.setBounds(640, 110, 181, 178);

        getContentPane().add(Friendspro);
        Friendspro.setBounds(890, 428, 434, 20);

        ViewProbtn.setText("Ver Perfil de Amigo");
        ViewProbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewProbtnMouseClicked(evt);
            }
        });
        getContentPane().add(ViewProbtn);
        ViewProbtn.setBounds(971, 394, 123, 23);

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 18));
        jLabel11.setText("Amigos");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(890, 394, 77, 18);

        Prooriginalbtn.setText("Regresar a mi perfil");
        Prooriginalbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProoriginalbtnMouseClicked(evt);
            }
        });
        getContentPane().add(Prooriginalbtn);
        Prooriginalbtn.setBounds(75, 543, 183, 23);

        getContentPane().add(Thougthscmb);
        Thougthscmb.setBounds(890, 200, 434, 20);
        getContentPane().add(jLabel10);
        jLabel10.setBounds(884, 148, 100, 0);

        jLabel12.setFont(new java.awt.Font("Tahoma", 3, 18));
        jLabel12.setText("    Status");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(1023, 170, 100, 24);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/face/imagess - copia.jpg"))); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(0, 0, 1340, 730);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DescripciontxtPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_DescripciontxtPropertyChange
       
        String name;
        
        
        
        try{
       RandomAccessFile PF=new RandomAccessFile("Cuentas/"+Profile.EmaildelAmigo+"/profile.fbn","rw");
       PF.seek(0);
       name=PF.readUTF();
       PF.seek(0);
       Descripciontxt.setText(name);
        }
        
        catch(Exception error){
            
            
        }
        
    }//GEN-LAST:event_DescripciontxtPropertyChange

    private void GenerotxtPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_GenerotxtPropertyChange
  
       char Genre;
        
        try{
       RandomAccessFile PF=new RandomAccessFile("Cuentas/"+Profile.EmaildelAmigo+"/profile.fbn","rw");
       PF.seek(0);
       PF.readUTF();
       Genre=PF.readChar();
       PF.seek(0);
        Generotxt.setText(Genre=='M'? "Masculino":"Femenino");
        }
        
        catch(Exception error){
            
            
        }
        
        
        
        
    }//GEN-LAST:event_GenerotxtPropertyChange

    private void NacimientotxtPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_NacimientotxtPropertyChange
        
      Long Naci;
      Date birth=null;
        
        try{
       RandomAccessFile PF=new RandomAccessFile("Cuentas/"+Profile.EmaildelAmigo+"/profile.fbn","rw");
       PF.seek(0);
       PF.readUTF();
       PF.readChar();
       Naci=PF.readLong();
       PF.seek(0);
       
       birth=new Date(Naci);
       
       Nacimientotxt.setText(birth.toString());
        }
        
        catch(Exception error){
            
            
        }
        
        
        
    }//GEN-LAST:event_NacimientotxtPropertyChange

    private void EmailtxtPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_EmailtxtPropertyChange
       
        String Ema;
        
        try{
       RandomAccessFile PF=new RandomAccessFile("Cuentas/"+Profile.EmaildelAmigo+"/profile.fbn","rw");
       PF.seek(0);
       PF.readUTF();
       PF.readChar();
       PF.readLong();
       Ema=PF.readUTF();
       PF.seek(0);
       Emailtxt.setText(Ema);
        }
        
        catch(Exception error){
            
            
        }
    }//GEN-LAST:event_EmailtxtPropertyChange

    private void IngresotxtPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_IngresotxtPropertyChange
        
         Long Ingres;
          Date llegada=null;        
         
        try{
       RandomAccessFile PF=new RandomAccessFile("Cuentas/"+Profile.EmaildelAmigo+"/profile.fbn","rw");
       PF.seek(0);
       PF.readUTF();
       PF.readChar();
       PF.readLong();
       PF.readUTF();
       Ingres=PF.readLong();
       PF.seek(0);
     
       
       llegada=new Date(Ingres);
       
       Ingresotxt.setText(llegada.toString());
        }
        
        catch(Exception error){
            
            
        }
        
        
    }//GEN-LAST:event_IngresotxtPropertyChange

    private void TelefonotxtPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_TelefonotxtPropertyChange
        
        int Phone;
        
        try{
         
            RandomAccessFile PF=new RandomAccessFile("Cuentas/"+Profile.EmaildelAmigo+"/profile.fbn","rw");
            PF.seek(0);
       PF.readUTF();
       PF.readChar();
       PF.readLong();
       PF.readUTF();
       PF.readLong();
       Phone=PF.readInt();
       PF.seek(0);
            
       Telefonotxt.setText(String.valueOf(Phone));
            
        }
        
        catch(Exception error){
            
            
            
            
        }
    }//GEN-LAST:event_TelefonotxtPropertyChange

    private void ImagetxtPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_ImagetxtPropertyChange
       
        
      
    }//GEN-LAST:event_ImagetxtPropertyChange

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        
        
    }//GEN-LAST:event_formMouseClicked

    private void ViewProbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewProbtnMouseClicked
       
        String amigo=Friendspro.getSelectedItem().toString();
        
        Profile.EmaildelAmigo=amigo;
        
        PerfilDeAmigo view=new PerfilDeAmigo();
        view.setVisible(true);
        dispose();
        
        
        
    }//GEN-LAST:event_ViewProbtnMouseClicked

    private void ProoriginalbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProoriginalbtnMouseClicked
       
        Perfil m=new Perfil();
        m.setVisible(true);
        dispose();
        
        
        
    }//GEN-LAST:event_ProoriginalbtnMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new PerfilDeAmigo().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Descripciontxt;
    private javax.swing.JLabel Emailtxt;
    private javax.swing.JComboBox Friendspro;
    private javax.swing.JLabel Generotxt;
    private javax.swing.JLabel Imagetxt;
    private javax.swing.JLabel Ingresotxt;
    private javax.swing.JLabel Nacimientotxt;
    private javax.swing.JButton Prooriginalbtn;
    private javax.swing.JLabel Telefonotxt;
    private javax.swing.JComboBox Thougthscmb;
    private javax.swing.JButton ViewProbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextPane jTextPane3;
    private javax.swing.JLabel lbl_Foto;
    private java.awt.ScrollPane scrollPane1;
    // End of variables declaration//GEN-END:variables

private ImageIcon getFoto(){
    JFileChooser chooser=new JFileChooser();
    chooser.setDialogTitle("");
    chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
   int opcion = chooser.showOpenDialog(this);
        if (opcion == JFileChooser.APPROVE_OPTION){

            String fotoPath = chooser.getSelectedFile().getAbsolutePath();
            ImageIcon foto= new ImageIcon(fotoPath);

            ImageIcon fotoReal1= new ImageIcon(foto.getImage().getScaledInstance(this.lbl_Foto.getWidth(), this.lbl_Foto.getHeight(), Image.SCALE_DEFAULT));
        
            return fotoReal1;
        }
        return null;



}

public void setFoto(){
ImageIcon foto= new ImageIcon("C:\\Users\\Josue\\Documents\\facebook-profile-picture.jpg");
ImageIcon fotoReal1= new ImageIcon(foto.getImage().getScaledInstance(this.lbl_Foto.getWidth(), this.lbl_Foto.getHeight(), Image.SCALE_DEFAULT));
this.lbl_Foto.setIcon(fotoReal1);
}



}
