/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Perfil.java
 *
 * Created on 11-28-2011, 02:44:01 PM
 */
package face;

import java.awt.Image;
import java.io.RandomAccessFile;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author Josue
 */
public class Perfil extends javax.swing.JFrame {

   
    

    public Perfil() {
        initComponents();
    this.lbl_Foto.setSize(200,200);
    setFoto();
    
    int contuni=0,posiciones=0,posfechas=0,total;
    Date m=null;
    
    
    try{
            
            String friend;
            
            boolean confirmado,decidido;
           RandomAccessFile amigos=new RandomAccessFile("Cuentas/"+Profile.Email+"/manageFriends.fbn","rw");
           amigos.seek(0);
           
           while(amigos.getFilePointer() < amigos.length()){
               
               friend=amigos.readUTF();
               confirmado=amigos.readBoolean();
               decidido=amigos.readBoolean();
               
               if(confirmado && decidido){
                   
                   Friendspro.addItem(friend);
               }
               
           }
           
            
            
        }
        catch(Exception error){
            
            
        }
    
    
   
    
    
    try{
    RandomAccessFile fg=new RandomAccessFile("Cuentas/"+Profile.Email+"/Status.fbn","rw");
    
      fg.seek(0);
      
       while(fg.getFilePointer() < fg.length()){
           
           fg.readUTF();
           contuni +=1;
           
       }
       
       total=contuni -1;
    
       
       
       fg.seek(0);
       
       String stats[]=new String[contuni];
       long Fechas[]=new long[contuni];
       
       while(fg.getFilePointer() < fg.length()){
           
           stats[posiciones]=fg.readUTF();
           posiciones +=1;
           
           
       }
       
       
       RandomAccessFile g=new RandomAccessFile("Cuentas/"+Profile.Email+"/Fechas.fbn","rw");
       
       g.seek(0);
       
       while(g.getFilePointer() < g.length()){
           
           Fechas[posfechas]=g.readLong();
           posfechas +=1;
           
       }
       
       
       
       int newcont=0;
       
       while(total >= 0){
       
       m= new Date(Fechas[total]);
         
       Statuscmb.addItem(stats[total]+"   "+m);
       
       total -=1;
       
       
       
       
       }
       
       
       
       
    
    }
    catch(Exception r){
        
    }
       
    
    
    
    
    
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jScrollBar1 = new javax.swing.JScrollBar();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        scrollPane1 = new java.awt.ScrollPane();
        Descripciontxt = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Generotxt = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Nacimientotxt = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Emailtxt = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Telefonotxt = new javax.swing.JLabel();
        Ingresotxt = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Versolicitudesbtn = new javax.swing.JButton();
        SendRequestbtn = new javax.swing.JButton();
        Modifiebtn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        Stattxt = new javax.swing.JTextField();
        Sumitbtn = new javax.swing.JButton();
        Salirbtn = new javax.swing.JButton();
        lbl_Foto = new javax.swing.JLabel();
        btnFoto = new javax.swing.JButton();
        Friendspro = new javax.swing.JComboBox();
        Verperfilbtn = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        Statuscmb = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jLabel7.setText("jLabel7");

        jScrollPane3.setViewportView(jTextPane1);

        jScrollPane4.setViewportView(jTextPane2);

        jScrollPane5.setViewportView(jTextPane3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1324, 734));
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(null);

        Descripciontxt.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        Descripciontxt.setForeground(new java.awt.Color(255, 255, 255));
        Descripciontxt.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                DescripciontxtPropertyChange(evt);
            }
        });
        getContentPane().add(Descripciontxt);
        Descripciontxt.setBounds(150, 110, 214, 17);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setText("GENERO:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 160, 90, 28);

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel3.setText("  NAME:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 110, 70, 22);

        Generotxt.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        Generotxt.setForeground(new java.awt.Color(255, 255, 255));
        Generotxt.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                GenerotxtPropertyChange(evt);
            }
        });
        getContentPane().add(Generotxt);
        Generotxt.setBounds(150, 160, 90, 29);

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel4.setText("FECHA DE NACIMIENTO:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 210, 230, 21);

        Nacimientotxt.setFont(new java.awt.Font("Times New Roman", 3, 14));
        Nacimientotxt.setForeground(new java.awt.Color(255, 255, 255));
        Nacimientotxt.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                NacimientotxtPropertyChange(evt);
            }
        });
        getContentPane().add(Nacimientotxt);
        Nacimientotxt.setBounds(270, 210, 350, 21);

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel6.setText("EMAIL:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 260, 80, 22);

        Emailtxt.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        Emailtxt.setForeground(new java.awt.Color(255, 255, 255));
        Emailtxt.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                EmailtxtPropertyChange(evt);
            }
        });
        getContentPane().add(Emailtxt);
        Emailtxt.setBounds(130, 250, 244, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel8.setText("FECHA DE INGRESO AL SISTEMA:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 310, 310, 26);

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel9.setText("TELEFONO:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(40, 360, 120, 19);

        Telefonotxt.setFont(new java.awt.Font("Times New Roman", 3, 14));
        Telefonotxt.setForeground(new java.awt.Color(255, 255, 255));
        Telefonotxt.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                TelefonotxtPropertyChange(evt);
            }
        });
        getContentPane().add(Telefonotxt);
        Telefonotxt.setBounds(160, 350, 231, 30);

        Ingresotxt.setFont(new java.awt.Font("Times New Roman", 3, 14));
        Ingresotxt.setForeground(new java.awt.Color(255, 255, 255));
        Ingresotxt.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                IngresotxtPropertyChange(evt);
            }
        });
        getContentPane().add(Ingresotxt);
        Ingresotxt.setBounds(300, 310, 320, 26);

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 24));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("                  MY BIN-STAT");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(320, 11, 477, 29);

        Versolicitudesbtn.setText("Aceptar solicitudes de amistad");
        Versolicitudesbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VersolicitudesbtnMouseClicked(evt);
            }
        });
        getContentPane().add(Versolicitudesbtn);
        Versolicitudesbtn.setBounds(75, 495, 209, 27);

        SendRequestbtn.setText("Mandar solicitud de amistad");
        SendRequestbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SendRequestbtnMouseClicked(evt);
            }
        });
        getContentPane().add(SendRequestbtn);
        SendRequestbtn.setBounds(75, 540, 209, 28);

        Modifiebtn.setText("Modificar Perfil");
        Modifiebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ModifiebtnMouseClicked(evt);
            }
        });
        getContentPane().add(Modifiebtn);
        Modifiebtn.setBounds(75, 579, 209, 26);

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel10.setText("STATUS:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(827, 121, 90, 22);
        getContentPane().add(Stattxt);
        Stattxt.setBounds(921, 118, 268, 20);

        Sumitbtn.setText("Submit");
        Sumitbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SumitbtnMouseClicked(evt);
            }
        });
        getContentPane().add(Sumitbtn);
        Sumitbtn.setBounds(1195, 117, 99, 23);

        Salirbtn.setText("Salir");
        Salirbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalirbtnMouseClicked(evt);
            }
        });
        getContentPane().add(Salirbtn);
        Salirbtn.setBounds(75, 466, 209, 23);

        lbl_Foto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(lbl_Foto);
        lbl_Foto.setBounds(630, 120, 181, 178);

        btnFoto.setText("Cambiar Foto");
        btnFoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFotoMouseClicked(evt);
            }
        });
        getContentPane().add(btnFoto);
        btnFoto.setBounds(660, 310, 121, 23);

        getContentPane().add(Friendspro);
        Friendspro.setBounds(875, 417, 350, 20);

        Verperfilbtn.setText("Ver Perfil de Amigo");
        Verperfilbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VerperfilbtnMouseClicked(evt);
            }
        });
        getContentPane().add(Verperfilbtn);
        Verperfilbtn.setBounds(978, 376, 170, 23);

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel11.setText("  Mis Amigos");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(848, 376, 120, 18);

        getContentPane().add(Statuscmb);
        Statuscmb.setBounds(875, 210, 395, 20);

        jLabel12.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel12.setText("What I'm thinking");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(951, 187, 170, 22);

        jLabel13.setFont(new java.awt.Font("Tahoma", 3, 14));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/face/imagess.jpg"))); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(-10, 0, 1330, 740);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DescripciontxtPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_DescripciontxtPropertyChange
       
        String name;
        
        
        
        try{
       RandomAccessFile PF=new RandomAccessFile("Cuentas/"+Profile.Email+"/profile.fbn","rw");
       PF.seek(0);
       name=PF.readUTF();
       PF.seek(0);
       Descripciontxt.setText(name);
        }
        
        catch(Exception error){
            
            
        }
        
    }//GEN-LAST:event_DescripciontxtPropertyChange

    private void GenerotxtPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_GenerotxtPropertyChange
  
       char Genre;
        
        try{
       RandomAccessFile PF=new RandomAccessFile("Cuentas/"+Profile.Email+"/profile.fbn","rw");
       PF.seek(0);
       PF.readUTF();
       Genre=PF.readChar();
       PF.seek(0);
        Generotxt.setText(Genre=='M'? "Masculino":"Femenino");
        }
        
        catch(Exception error){
            
            
        }
        
        
        
        
    }//GEN-LAST:event_GenerotxtPropertyChange

    private void NacimientotxtPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_NacimientotxtPropertyChange
        
      Long Naci;
      Date birth=null;
        
        try{
       RandomAccessFile PF=new RandomAccessFile("Cuentas/"+Profile.Email+"/profile.fbn","rw");
       PF.seek(0);
       PF.readUTF();
       PF.readChar();
       Naci=PF.readLong();
       PF.seek(0);
       
       birth=new Date(Naci);
       
       Nacimientotxt.setText(birth.toString());
        }
        
        catch(Exception error){
            
            
        }
        
        
        
    }//GEN-LAST:event_NacimientotxtPropertyChange

    private void EmailtxtPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_EmailtxtPropertyChange
       
        String Ema;
        
        try{
       RandomAccessFile PF=new RandomAccessFile("Cuentas/"+Profile.Email+"/profile.fbn","rw");
       PF.seek(0);
       PF.readUTF();
       PF.readChar();
       PF.readLong();
       Ema=PF.readUTF();
       PF.seek(0);
       Emailtxt.setText(Ema);
        }
        
        catch(Exception error){
            
            
        }
    }//GEN-LAST:event_EmailtxtPropertyChange

    private void IngresotxtPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_IngresotxtPropertyChange
        
         Long Ingres;
          Date llegada=null;        
         
        try{
       RandomAccessFile PF=new RandomAccessFile("Cuentas/"+Profile.Email+"/profile.fbn","rw");
       PF.seek(0);
       PF.readUTF();
       PF.readChar();
       PF.readLong();
       PF.readUTF();
       Ingres=PF.readLong();
       PF.seek(0);
     
       
       llegada=new Date(Ingres);
       
       Ingresotxt.setText(llegada.toString());
        }
        
        catch(Exception error){
            
            
        }
        
        
    }//GEN-LAST:event_IngresotxtPropertyChange

    private void TelefonotxtPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_TelefonotxtPropertyChange
        
        int Phone;
        
        try{
         
            RandomAccessFile PF=new RandomAccessFile("Cuentas/"+Profile.Email+"/profile.fbn","rw");
            PF.seek(0);
       PF.readUTF();
       PF.readChar();
       PF.readLong();
       PF.readUTF();
       PF.readLong();
       Phone=PF.readInt();
       PF.seek(0);
            
       Telefonotxt.setText(String.valueOf(Phone));
            
        }
        
        catch(Exception error){
            
            
            
            
        }
    }//GEN-LAST:event_TelefonotxtPropertyChange

    private void SendRequestbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SendRequestbtnMouseClicked
        
        Enviar_Solicitudes env=new Enviar_Solicitudes();
        env.setVisible(true);
        dispose();
    }//GEN-LAST:event_SendRequestbtnMouseClicked

    private void ModifiebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModifiebtnMouseClicked

          Modificar_Perfil mp=new Modificar_Perfil();
          mp.setVisible(true);
          dispose();
        
    }//GEN-LAST:event_ModifiebtnMouseClicked

    private void SumitbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SumitbtnMouseClicked

       try{
           
      Long fechapost;
      Date d=new Date();
      
      
      RandomAccessFile raf=new RandomAccessFile("Cuentas/"+Profile.Email+"/Status.fbn","rw");
       raf.seek(raf.length());
       
       raf.writeUTF(Stattxt.getText());
       
       
       RandomAccessFile da=new RandomAccessFile("Cuentas/"+Profile.Email+"/Fechas.fbn","rw");
       da.seek(da.length());
       
       da.writeLong(d.getTime());
       
       
       Perfil o=new Perfil();
       o.setVisible(true);
       dispose();
       
           
       }
       catch(Exception error){
           
           
       }
        
        
    }//GEN-LAST:event_SumitbtnMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        
        
    }//GEN-LAST:event_formMouseClicked

    private void VersolicitudesbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VersolicitudesbtnMouseClicked
        
         Listar_Solicitudes_de_Amistad lsa=new Listar_Solicitudes_de_Amistad();
         lsa.setVisible(true);
         dispose();
    }//GEN-LAST:event_VersolicitudesbtnMouseClicked

    private void SalirbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirbtnMouseClicked
  LogIn f=new LogIn();
  f.setVisible(true);
  dispose();
        
    }//GEN-LAST:event_SalirbtnMouseClicked

    private void btnFotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFotoMouseClicked
        // TODO add your handling code here:

        ImageIcon foto=this.getFoto();
        
        if(foto!=null){
        this.lbl_Foto.setIcon(foto);
        }
        else{
        JOptionPane.showMessageDialog(this,"Ocurrio un error");
        }
        
    }//GEN-LAST:event_btnFotoMouseClicked

    private void VerperfilbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VerperfilbtnMouseClicked
       
        String amigo=Friendspro.getSelectedItem().toString();
        
        Profile.EmaildelAmigo=amigo;
        
        PerfilDeAmigo view=new PerfilDeAmigo();
        view.setVisible(true);
        dispose();
        
        
        
    }//GEN-LAST:event_VerperfilbtnMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Perfil().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Descripciontxt;
    private javax.swing.JLabel Emailtxt;
    private javax.swing.JComboBox Friendspro;
    private javax.swing.JLabel Generotxt;
    private javax.swing.JLabel Ingresotxt;
    private javax.swing.JButton Modifiebtn;
    private javax.swing.JLabel Nacimientotxt;
    private javax.swing.JButton Salirbtn;
    private javax.swing.JButton SendRequestbtn;
    private javax.swing.JTextField Stattxt;
    private javax.swing.JComboBox Statuscmb;
    private javax.swing.JButton Sumitbtn;
    private javax.swing.JLabel Telefonotxt;
    private javax.swing.JButton Verperfilbtn;
    private javax.swing.JButton Versolicitudesbtn;
    private javax.swing.JButton btnFoto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextPane jTextPane3;
    private javax.swing.JLabel lbl_Foto;
    private java.awt.ScrollPane scrollPane1;
    // End of variables declaration//GEN-END:variables

private ImageIcon getFoto(){
    JFileChooser chooser=new JFileChooser();
    chooser.setDialogTitle("");
    chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
   int opcion = chooser.showOpenDialog(this);
        if (opcion == JFileChooser.APPROVE_OPTION){

            String fotoPath = chooser.getSelectedFile().getAbsolutePath();
            ImageIcon foto= new ImageIcon(fotoPath);

            ImageIcon fotoReal1= new ImageIcon(foto.getImage().getScaledInstance(this.lbl_Foto.getWidth(), this.lbl_Foto.getHeight(), Image.SCALE_DEFAULT));
        
            return fotoReal1;
        }
        return null;



}

public void setFoto(){
ImageIcon foto= new ImageIcon("C:\\Users\\Josue\\Pictures\\user2.png");
ImageIcon fotoReal1= new ImageIcon(foto.getImage().getScaledInstance(this.lbl_Foto.getWidth(), this.lbl_Foto.getHeight(), Image.SCALE_DEFAULT));
this.lbl_Foto.setIcon(fotoReal1);
}



}
