/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Registro.java
 *
 * Created on 11-24-2011, 05:35:41 PM
 */
package face;

import java.io.File;
import java.io.RandomAccessFile;
import java.util.Date;
import javax.swing.JOptionPane;
/**
 *
 * @author Josue
 */
public class Registro extends javax.swing.JFrame {

    /** Creates new form Registro */
    public Registro() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        Fechadenacimientotxt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        Entradatxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Maculinocb = new javax.swing.JCheckBox();
        Femeninocb = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        Generoscmb = new javax.swing.JComboBox();
        Statustxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Generotxt = new javax.swing.JTextField();
        Aniotxt = new javax.swing.JTextField();
        Mestxt = new javax.swing.JTextField();
        Diatxt = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Nombretxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Emailregitxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Telefonotxt = new javax.swing.JTextField();
        CrearPerfiltxt = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        Passwordtxt = new javax.swing.JPasswordField();
        jLabel15 = new javax.swing.JLabel();
        Genrecmb = new javax.swing.JComboBox();
        Yearcmb = new javax.swing.JComboBox();
        Monthcmb = new javax.swing.JComboBox();
        Daycmb = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        jLabel3.setText(" ");

        jLabel13.setText("jLabel13");

        jLabel7.setText("Fecha de entrada al sistema:");

        Maculinocb.setText("Masculino");
        Maculinocb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MaculinocbMouseClicked(evt);
            }
        });

        Femeninocb.setText("Femenino");
        Femeninocb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FemeninocbMouseClicked(evt);
            }
        });

        jLabel4.setText(" Genero:");

        Generoscmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Generoscmb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GeneroscmbMouseClicked(evt);
            }
        });
        Generoscmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeneroscmbActionPerformed(evt);
            }
        });

        jLabel9.setText("Status:");

        jLabel16.setText("jLabel16");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(966, 491));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("   Nombre:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 100, 70, 24);

        Nombretxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombretxtActionPerformed(evt);
            }
        });
        getContentPane().add(Nombretxt);
        Nombretxt.setBounds(110, 100, 246, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Fecha de nacimiento");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 204, 130, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Email:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(28, 320, 40, 20);
        getContentPane().add(Emailregitxt);
        Emailregitxt.setBounds(70, 320, 343, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Telefono:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(450, 100, 70, 15);
        getContentPane().add(Telefonotxt);
        Telefonotxt.setBounds(519, 100, 370, 20);

        CrearPerfiltxt.setText("Registrarse");
        CrearPerfiltxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CrearPerfiltxtMouseClicked(evt);
            }
        });
        CrearPerfiltxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearPerfiltxtActionPerformed(evt);
            }
        });
        getContentPane().add(CrearPerfiltxt);
        CrearPerfiltxt.setBounds(660, 220, 122, 23);

        jLabel14.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Password:");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(450, 160, 70, 15);

        Passwordtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordtxtActionPerformed(evt);
            }
        });
        getContentPane().add(Passwordtxt);
        Passwordtxt.setBounds(530, 160, 335, 20);

        jLabel15.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Genero:");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(39, 160, 50, 15);

        Genrecmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "  ", "Masculino", "Femenino" }));
        getContentPane().add(Genrecmb);
        Genrecmb.setBounds(90, 160, 133, 20);

        Yearcmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "  ", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970" }));
        getContentPane().add(Yearcmb);
        Yearcmb.setBounds(240, 250, 126, 20);

        Monthcmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        getContentPane().add(Monthcmb);
        Monthcmb.setBounds(90, 250, 126, 20);

        Daycmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        getContentPane().add(Daycmb);
        Daycmb.setBounds(20, 250, 50, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/face/s - copia (3).jpg"))); // NOI18N
        jLabel1.setText("D");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -30, 970, 550);

        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(20, 230, 40, 14);

        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(20, 230, 40, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CrearPerfiltxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearPerfiltxtMouseClicked
       
  
  String EmailEntrante,Genero;
  String EmailGuardado,PasswordEntrante;
  boolean coincidencia=false,activo=false;
  
  int repose=0;
  String repo;
  
  
  
  int index,anio=0;
  int dia;
  int mes=0;
  
  String Periodo;
  
  
  
  EmailEntrante=Emailregitxt.getText();
  Genero=Genrecmb.getSelectedItem().toString();
  PasswordEntrante=Passwordtxt.getText();
  
  
   
  try{
  
  RandomAccessFile Ger=new RandomAccessFile("Gerencia.fbn","rw");
  Ger.seek(0);
  
  while(Ger.getFilePointer() < Ger.length()){
      
      EmailGuardado=Ger.readUTF();
      Ger.readUTF();
      activo=Ger.readBoolean();
      
      if(EmailEntrante.equals(EmailGuardado)){
          
          if(activo){
          
          coincidencia=true;
          break;
          
          }else{
              
              coincidencia=false;
              repose+=1;
              break;
          }
          
      }else{
          coincidencia=false;
      }
      
     
  
  }
  
  
  
  if(repose == 1 && !coincidencia){
         
         
         
          dia=Daycmb.getSelectedIndex()+1 ;
          
          Periodo=Monthcmb.getSelectedItem().toString() ;
          
          if(Periodo.equals("Enero")){
              
              mes+=1;
          }else if(Periodo.equals("Febrero")){
              mes+=2;
          }else if(Periodo.equals("Marzo")){
              mes+=3;
          }else if(Periodo.equals("Abril")){
              mes+=4;
          }else if(Periodo.equals("Mayo")){
              mes+=5;
          }else if(Periodo.equals("Junio")){
              mes+=6;
          }else if(Periodo.equals("Julio")){
              mes+=7;
          }else if(Periodo.equals("Agosto")){
              mes+=8;
          }else if(Periodo.equals("Septiembre")){
              mes+=9;
          }else if(Periodo.equals("Octubre")){
              mes+=10;
          }else if(Periodo.equals("Noviembre")){
              mes+=11;
              
          }else if(Periodo.equals("Diciembre")){
              mes+=12;
          }
          
          
          index=Yearcmb.getSelectedIndex();
         
         if(index == 0){
                
                anio=2011;
            }else if(index == 1){
                anio+=2010;
            }else if(index ==2){
                anio+=2009;
            }else if(index ==3){
                anio+=2008;
            }else if(index ==4){
                anio+=2007;
            }else if(index ==5){
                anio+=2006;
            }else if(index ==6){
                anio+=2005;
            }else if(index ==7){
                anio+=2004;
            }else if(index ==8){
                anio+=2003;
            }else if(index ==9){
                anio+=2002;
            }else if(index ==10){
                anio+=2001;
            }else if(index ==11){
                anio+=2000;
            }else if(index ==12){
                anio+=1999;
            }else if(index ==13){
                anio+=1998;
            }else if(index ==14){
                anio+=1997;
            }else if(index ==15){
                anio+=1996;
            }else if(index ==16){
                anio+=1995;
            }else if(index ==17){
                anio+=1994;
            }else if(index ==18){
                anio+=1993;
            }else if(index ==19){
                anio+=1992;
            }else if(index ==20){
                anio+=1991;
            }else if(index == 21){
                anio+=1990;
            }else if(index == 22){
                
                anio+=1989;
            }else if(index == 23){
                
                anio+=1988;
            }else if(index == 24){
                
                anio+=1987;
            }else if(index == 25){
                
                anio+=1986;
            }else if(index == 26){
                
                anio+=1985;
            }else if(index == 27){
                
                anio+=1984;
            }else if(index == 28){
                
                anio+=1983;
            }else if(index == 29){
                
                anio+=1982;
            }else if(index == 30){
                
                anio+=1981;
            }else if(index == 31){
                
                 anio+=1980;
            }else if( index == 32){
                
                anio+=1979;
            }else if( index == 33){
                
                anio+=1978;
            }else if( index == 34){
                
                anio+=1977;
            }else if( index == 35){
                
                anio+=1976;
            }else if( index == 36){
                
                anio+=1975;
            }else if( index == 37){
                
                anio+=1974;
            }else if( index == 38){
                
                anio+=1973;
            }else if( index == 39){
                
                anio+=1972;
            }else if( index == 40){
                
                anio+=1971;
            }else if( index == 41){
                
                anio+=1970;
            }
         
         
       Profile.Email=EmailEntrante;
         
         SetRegistro sr=new SetRegistro();
         
         sr.setFechadeNacimiento(dia,mes-1,anio);
         
         Ger.seek(0);
         
         while(Ger.getFilePointer() < Ger.length()){
         
         repo=Ger.readUTF();
         
         if(repo.equals(Profile.Email)){
         
         Ger.writeUTF(PasswordEntrante);
         Ger.writeBoolean(true);
         break;
         
         }
         
         Ger.readUTF();
         Ger.readBoolean();
         
         
         }
         
         File fold=new File("Cuentas/"+EmailEntrante);
         fold.mkdirs();
         
         RandomAccessFile pro=new RandomAccessFile("Cuentas/"+EmailEntrante+"/profile.fbn","rw");
         RandomAccessFile MF=new RandomAccessFile("Cuentas/"+EmailEntrante+"/manageFriends.fbn","rw");
         RandomAccessFile Post=new RandomAccessFile("Cuentas/"+EmailEntrante+"/Status.fbn","rw");
         RandomAccessFile days=new RandomAccessFile("Cuentas/"+EmailEntrante+"/Fechas.fbn","rw");
         
         pro.writeUTF(Nombretxt.getText());
         
         if(Genero.equals("Masculino")){
         pro.writeChar('M');
         }else{
         pro.writeChar('F');
             
         }
      
         pro.writeLong(sr.FechadeNacimiento.getTime());
         pro.writeUTF(Emailregitxt.getText());
         pro.writeLong(sr.Ahorita.getTime());
         pro.writeInt(Integer.parseInt(Telefonotxt.getText()));
         pro.writeUTF(Statustxt.getText());
         
         
         
         
       
         JOptionPane.showMessageDialog(null, "La cuenta fue creada correctamente !!",
                "Informacion de Cuenta", JOptionPane.INFORMATION_MESSAGE);
         
         
         VerPerfil vp=new VerPerfil();
             vp.setVisible(true);
             dispose();
         
         
         
     }
  
  
  
 
  
     if((!coincidencia) && repose== 0){
         
         
         
          dia=Daycmb.getSelectedIndex()+1 ;
          
          Periodo=Monthcmb.getSelectedItem().toString() ;
          
          if(Periodo.equals("Enero")){
              
              mes+=1;
          }else if(Periodo.equals("Febrero")){
              mes+=2;
          }else if(Periodo.equals("Marzo")){
              mes+=3;
          }else if(Periodo.equals("Abril")){
              mes+=4;
          }else if(Periodo.equals("Mayo")){
              mes+=5;
          }else if(Periodo.equals("Junio")){
              mes+=6;
          }else if(Periodo.equals("Julio")){
              mes+=7;
          }else if(Periodo.equals("Agosto")){
              mes+=8;
          }else if(Periodo.equals("Septiembre")){
              mes+=9;
          }else if(Periodo.equals("Octubre")){
              mes+=10;
          }else if(Periodo.equals("Noviembre")){
              mes+=11;
              
          }else if(Periodo.equals("Diciembre")){
              mes+=12;
          }
          
          
          index=Yearcmb.getSelectedIndex();
         
         if(index == 0){
                
                anio=2011;
            }else if(index == 1){
                anio+=2010;
            }else if(index ==2){
                anio+=2009;
            }else if(index ==3){
                anio+=2008;
            }else if(index ==4){
                anio+=2007;
            }else if(index ==5){
                anio+=2006;
            }else if(index ==6){
                anio+=2005;
            }else if(index ==7){
                anio+=2004;
            }else if(index ==8){
                anio+=2003;
            }else if(index ==9){
                anio+=2002;
            }else if(index ==10){
                anio+=2001;
            }else if(index ==11){
                anio+=2000;
            }else if(index ==12){
                anio+=1999;
            }else if(index ==13){
                anio+=1998;
            }else if(index ==14){
                anio+=1997;
            }else if(index ==15){
                anio+=1996;
            }else if(index ==16){
                anio+=1995;
            }else if(index ==17){
                anio+=1994;
            }else if(index ==18){
                anio+=1993;
            }else if(index ==19){
                anio+=1992;
            }else if(index ==20){
                anio+=1991;
            }else if(index == 21){
                anio+=1990;
            }else if(index == 22){
                
                anio+=1989;
            }else if(index == 23){
                
                anio+=1988;
            }else if(index == 24){
                
                anio+=1987;
            }else if(index == 25){
                
                anio+=1986;
            }else if(index == 26){
                
                anio+=1985;
            }else if(index == 27){
                
                anio+=1984;
            }else if(index == 28){
                
                anio+=1983;
            }else if(index == 29){
                
                anio+=1982;
            }else if(index == 30){
                
                anio+=1981;
            }else if(index == 31){
                
                 anio+=1980;
            }else if( index == 32){
                
                anio+=1979;
            }else if( index == 33){
                
                anio+=1978;
            }else if( index == 34){
                
                anio+=1977;
            }else if( index == 35){
                
                anio+=1976;
            }else if( index == 36){
                
                anio+=1975;
            }else if( index == 37){
                
                anio+=1974;
            }else if( index == 38){
                
                anio+=1973;
            }else if( index == 39){
                
                anio+=1972;
            }else if( index == 40){
                
                anio+=1971;
            }else if( index == 41){
                
                anio+=1970;
            }
         
         
       Profile.Email=EmailEntrante;
         
         SetRegistro sr=new SetRegistro();
         
         sr.setFechadeNacimiento(dia,mes-1,anio);
         
         Ger.seek(Ger.length());
         
         Ger.writeUTF(EmailEntrante);
         Ger.writeUTF(PasswordEntrante);
         Ger.writeBoolean(true);
         
         File fold=new File("Cuentas/"+EmailEntrante);
         fold.mkdirs();
         
         RandomAccessFile pro=new RandomAccessFile("Cuentas/"+EmailEntrante+"/profile.fbn","rw");
         RandomAccessFile MF=new RandomAccessFile("Cuentas/"+EmailEntrante+"/manageFriends.fbn","rw");
         RandomAccessFile Post=new RandomAccessFile("Cuentas/"+EmailEntrante+"/Status.fbn","rw");
         RandomAccessFile days=new RandomAccessFile("Cuentas/"+EmailEntrante+"/Fechas.fbn","rw");
         
         pro.writeUTF(Nombretxt.getText());
         
         if(Genero.equals("Masculino")){
         pro.writeChar('M');
         }else{
         pro.writeChar('F');
             
         }
      
         pro.writeLong(sr.FechadeNacimiento.getTime());
         pro.writeUTF(Emailregitxt.getText());
         pro.writeLong(sr.Ahorita.getTime());
         pro.writeInt(Integer.parseInt(Telefonotxt.getText()));
         pro.writeUTF(Statustxt.getText());
         
         
         
         
       
         JOptionPane.showMessageDialog(null, "La cuenta fue creada correctamente !!",
                "Informacion de Cuenta", JOptionPane.INFORMATION_MESSAGE);
         
         
         VerPerfil vp=new VerPerfil();
             vp.setVisible(true);
             dispose();
         
         
         
     }
     else{ 
         
      JOptionPane.showMessageDialog(null, "EMAIL YA USADO!VUELVA INTENTAR !!",
                "Informacion de Cuenta", JOptionPane.INFORMATION_MESSAGE);
     }
  
  }
  
  catch(Exception error){
   
      
  }
       
   
   
    }//GEN-LAST:event_CrearPerfiltxtMouseClicked

    private void MaculinocbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MaculinocbMouseClicked
      
        
    }//GEN-LAST:event_MaculinocbMouseClicked

    private void FemeninocbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FemeninocbMouseClicked
      
       
    }//GEN-LAST:event_FemeninocbMouseClicked

    private void CrearPerfiltxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearPerfiltxtActionPerformed
     
        
        
        
    }//GEN-LAST:event_CrearPerfiltxtActionPerformed

    private void GeneroscmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeneroscmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GeneroscmbActionPerformed

    private void GeneroscmbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GeneroscmbMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_GeneroscmbMouseClicked

    private void PasswordtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordtxtActionPerformed

    private void NombretxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombretxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombretxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Registro().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Aniotxt;
    private javax.swing.JButton CrearPerfiltxt;
    private javax.swing.JComboBox Daycmb;
    private javax.swing.JTextField Diatxt;
    private javax.swing.JTextField Emailregitxt;
    private javax.swing.JTextField Entradatxt;
    private javax.swing.JTextField Fechadenacimientotxt;
    private javax.swing.JCheckBox Femeninocb;
    private javax.swing.JComboBox Generoscmb;
    private javax.swing.JTextField Generotxt;
    private javax.swing.JComboBox Genrecmb;
    private javax.swing.JCheckBox Maculinocb;
    private javax.swing.JTextField Mestxt;
    private javax.swing.JComboBox Monthcmb;
    private javax.swing.JTextField Nombretxt;
    private javax.swing.JPasswordField Passwordtxt;
    private javax.swing.JTextField Statustxt;
    private javax.swing.JTextField Telefonotxt;
    private javax.swing.JComboBox Yearcmb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSpinner jSpinner1;
    // End of variables declaration//GEN-END:variables
}
