/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VerPerfil.java
 *
 * Created on 11-25-2011, 08:13:25 PM
 */
package face;

/**
 *
 * @author Josue
 */
public class VerPerfil extends javax.swing.JFrame {

    /** Creates new form VerPerfil */
    public VerPerfil() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        Verperfilbtn = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setText("    Conectate a traves de FaceBin para estar al tanto de tus amistades");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(625, 450));
        setResizable(false);
        getContentPane().setLayout(null);

        Verperfilbtn.setFont(new java.awt.Font("Tahoma", 0, 18));
        Verperfilbtn.setText("Ir a Perfil");
        Verperfilbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VerperfilbtnMouseClicked(evt);
            }
        });
        getContentPane().add(Verperfilbtn);
        Verperfilbtn.setBounds(360, 350, 199, 31);

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jTextField1.setText("  BIENVENIDOS A FACEBIN  ");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(40, 10, 550, 60);

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextField2.setText("El lugar donde estas en contacto con todos");
        getContentPane().add(jTextField2);
        jTextField2.setBounds(40, 60, 550, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/face/social-networking-625x450.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 630, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VerperfilbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VerperfilbtnMouseClicked
       
        DatosdelAmigo.encontrado=false;
        Perfil per=new Perfil();
        
        per.setVisible(true);
        dispose();
    }//GEN-LAST:event_VerperfilbtnMouseClicked

private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new VerPerfil().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Verperfilbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
